### ISSUE TITLE
[BUG] User info appears behind avatar

### ISSUE THREAD

**Issue by leuconxyz** [Slddev/ModernX-Theme#28]
### Description of bug

![DiscordCanary_ORgh15XVh1](https://user-images.githubusercontent.com/63231736/178364304-0d9a92a3-9c1d-48f3-af94-39aa0c007762.png)

The user discord name and or nickname appears behind their avatar since last update for some reason

### Steps to reproduce

click someone to pull up their info.

### Suspected cause

Update

### Screenshots

![DiscordCanary_mqI0bxUyt4](https://user-images.githubusercontent.com/63231736/178364414-1fe1bbf7-50ad-462a-b559-e246c22f4ae0.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by HDTRPlayzZ-Git** [comment]
I have the same issue

**Comment by Slddev** [comment]
Fixed in [`930505a`](https://github.com/Slddev/ModernX-Theme/commit/930505a4fd2c59d3d34aa33c244b24af97bf260d).

**Comment by leuconxyz** [comment]
Issue fixed for users without banner, issue still exists on users WITH banner.

Without Nanner: 
![DiscordCanary_uid7Zdw7Ap](https://user-images.githubusercontent.com/63231736/180568756-5a66909a-6aa6-455f-ab81-42b8578040a0.png)

**With** Banner:
![DiscordCanary_tXjGDHMsjK](https://user-images.githubusercontent.com/63231736/180568805-66a6e2bd-e667-490d-8e20-ba52e926fbb1.png)
